@startuml
'https://plantuml.com/class-diagram

class CartaPokemon {
    -- Atributs --
    - nom: String
    - tipus: TipusPokemon
    - puntsAtac: Int
    - puntsDefensa: Int
    -- Mètodes --
    + CartaPokemon(String, TipusPokemon, Int,  Int)
    + getNom(): String
    + poderTotal(): Int
    + compararPoder(poderTotal(), CartaPokemon): RetornComparacio
}


class JugadorPokemon {
    -- Atributs --
    - nom: String
    - cartes: List<CartaPokemon>
    -- Metodes --
    + constructor(String, List<CartaPokemon>)
}

enum TipusPokemon {
    foc
    aigua
    planta
    electric
}

enum RetornComparacio {
    0
    1
    2
}



CartaPokemon *-down- JugadorPokemon
CartaPokemon "N" *-left- "1" TipusPokemon : és
CartaPokemon "1" *-right- "1" RetornComparacio


@enduml