@startuml
'https://plantuml.com/class-diagram

class BegudaMonster {
    -- Atributs --
    - sabor: String
    - qCafeina: Int
    - colors: String
    - volum: Int
    -- Mètodes --


}

class Participant {
    -- Atributs --
    - nom: String
    - edat: Int
    - totalCafeina: Float
    - begudesConsumides: List<BegudaMonster>
    -- Mètodes --
    + constructor(nom: String, dataNaixement: LocalDate, totalCafeina: Float,  begudesConsumides: List<BegudaMonster>)
    + registrar (nova: List<BegudaMonster>): List<BegudaMonster>
    + consultarCafeina (totalCafeina: Float): Float
    + calcularEdat (dataNaixement: LocalDate): Int
    + LimitOMS (totalCafeina: Float): Boolean
}

@enduml