@startuml
'https://plantuml.com/class-diagram

class BegudaMonster {
    -- Atributs --
    - sabor: String
    - qCafeina: Int
    - colors: String
    - volum: Int
    -- Mètodes --
    + constructor(String, Int, String, Int)
    + getCafeina(): Int


}

class Participant {
    -- Atributs --
    - nom: String
    - edat: date
    - totalCafeina: Float
    - begudesConsumides: List<BegudaMonster>
    -- Mètodes --
    + constructor(String, dataNaixement: LocalDate, totalCafeina: Float,  begudesConsumides: List<BegudaMonster>)
    + registrar (BegudaMonster)
    + getConsultarCafeina(): Float
    + calcularEdat (): Int
    + limitOMS (): Boolean
    - recalcularTotalCafeina(): Float
}
Participant "1" o-down- "N" BegudaMonster: Consumeix


@enduml