@startuml
'https://plantuml.com/class-diagram


class PeçaDeRoba {
    -- Atributs --
    - nom: String
    - talla: Int
    - preu: Float
    - categoria: String
    -- Mètodes --
     + constructor(nom: String, talla: String, preu: Float, categoria: String)
    + aplicarDescompte(preu):Float
    + getConsulta(): String

}

class Client {
    -- Atributs --
    - nom: String
    - email: String
    - cistella: List<PeçaDeRoba>
    -- Mètodes --
    + afegirPeça(carret: List<PeçaDeRoba>)
    + totalPreu(carret: List<PeçaDeRoba>): Int
}

@enduml